CREATE TABLE CLIENTE(
    ID SERIAL NOT NULL PRIMARY KEY,
    NOME VARCHAR(100)
);

CREATE TABLE PRODUTO(
    ID SERIAL NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(100),
    PRECO_UNITARIO NUMERIC(20,2)
);

CREATE TABLE PEDIDO(
    ID SERIAL NOT NULL PRIMARY KEY,
    ID_CLIENTE INTEGER REFERENCES CLIENTE(ID),
    DATA_PEDIDO TIMESTAMP,
    TOTAL NUMERIC(20,2)
);

CREATE TABLE ITEM_PEDIDO(
    ID SERIAL NOT NULL PRIMARY KEY,
    ID_PEDIDO INTEGER REFERENCES PEDIDO(ID),
    ID_PRODUTO INTEGER REFERENCES PRODUTO(ID),
    QUANTIDADE INT
);